url: https://lecuyer-a.github.io
baseurl: /

# Site settings
title: Alison Lecuyer
email: alison.lecuyer@etu.unice.fr
description: "Personal resume and portfolio."

member: 
    name: Alison Lecuyer 
    pic: alison
    short: Passionate about programming, I wish from a young age to work in IT. 
    birth: 18/10/2000
    language:
    - title: French
      level: Native
    - title: English 
      level: Professional 
    - title: Spanish 
      level: Notions 
    - title: Japanese 
      level: Notions 
    mail: alison.lecuyer@etu.unice.fr
    phone: 0786350474
    address: 185 chemin de la Costière, 06000, Nice, France 
    social:
    - title: github
      url: https://github.com/lecuyer-a
    - title: linkedin
      url: https://www.linkedin.com/in/alison-lecuyer/
      

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket 
    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: France, Nice, 06000 
  - line: 185 chemin de la Costière

# Build settings
markdown: kramdown
permalink: pretty